name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.10.0

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Generate timestamp tag
      run: echo "TIMESTAMP=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.15.0
      with:
        context: .
        push: true
        tags: |
          stellatezero/atext-api:latest
          stellatezero/atext-api:${{ env.TIMESTAMP }}
